import os
import json
import subprocess
import html
from datetime import datetime

_last_summary_cache = {}

def register_ai_handlers(bot):
    
    @bot.message_handler(commands=['read'])
    def read_handle(message):
        parts = message.text.strip().split(None, 2)
        if len(parts) < 2:
            bot.reply_to(message,
                "📖 *Cách dùng:*\n"
                "`/read <url>` — Chạy AI Pipeline Tóm tắt & Dịch bài\n"
                "`/read <url> <yêu cầu>` — Chạy Pipeline với yêu cầu riêng\n\n"
                "*Ví dụ:*\n"
                "`/read https://mp.weixin.qq.com/...`\n"
                "`/read https://mp... Tóm tắt chi tiết ra 10 gạch đầu dòng`",
                parse_mode="Markdown")
            return
            
        url = parts[1].strip()
        custom_prompt = parts[2].strip() if len(parts) > 2 else ""
        if not url.startswith("http"):
            bot.reply_to(message, "❌ URL không hợp lệ. Phải bắt đầu bằng `http` hoặc `https`.", parse_mode="Markdown")
            return
            
        wait_msg = bot.reply_to(message, "⏳ Đang kích hoạt 🤖 AI News Pipeline (Node.js)...")
        
        # Check OS to run npx correctly
        npx_cmd = "npx.cmd" if os.name == "nt" else "npx"
        
        try:
            # Run the TypeScript Pipeline Bundle
            cmd_args = [npx_cmd, "tsx", "ai-news-bundle.ts", "--url", url]
            if custom_prompt:
                cmd_args.extend(["--prompt", custom_prompt])
                
            proc = subprocess.run(
                cmd_args,
                capture_output=True, text=True, encoding="utf-8", cwd=os.getcwd()
            )
            
            stdout_str = proc.stdout if proc.stdout else ""
            stderr_str = proc.stderr if proc.stderr else ""
            
            # Log backend TS execution to console
            print(stdout_str)
            if stderr_str:
                print("STDERR:", stderr_str)
                
            json_file = "ai_news_output.json"
            
            if os.path.exists(json_file):
                with open(json_file, "r", encoding="utf-8") as f:
                    article = json.load(f)
                    
                title = article.get("title", "Không rõ tiêu đề")
                content = article.get("content", "")
                
                safe_title = html.escape(title[:120])
                safe_url = html.escape(url)
                
                # Keep HTML tags like <b>, <i> generated by Gemini for Telegram formatting
                clean_content = content.strip()
                if not clean_content:
                    clean_content = article.get("excerpt", "Tóm tắt trắng")
                    
                _last_summary_cache[message.chat.id] = {"title": title, "summary": clean_content, "url": url}
                
                response = (
                    f"📰 <b>{safe_title}</b>\n"
                    f"🔗 {safe_url}\n"
                    f"{'─' * 28}\n\n"
                    f"{clean_content}\n\n"
                    f"{'─' * 28}\n"
                    f"<i>Gõ /infographic để tạo ảnh tóm tắt</i>"
                )
                bot.edit_message_text(response, message.chat.id, wait_msg.message_id, parse_mode="HTML")
                
                # Remove temp file
                try:
                    os.remove(json_file)
                except Exception:
                    pass
            else:
                # If fail, send the last few lines of the typescript output
                err_log = "\n".join(stdout_str.split("\n")[-10:])
                bot.edit_message_text(f"❌ Pipeline chạy thất bại.\nSTDOUT:\n```\n{err_log}\n```\nSTDERR:\n```\n{stderr_str[:500]}\n```", message.chat.id, wait_msg.message_id, parse_mode="Markdown")
                
        except Exception as e:
            bot.edit_message_text(f"❌ Lỗi thực thi Pipeline: {e}", message.chat.id, wait_msg.message_id)

    @bot.message_handler(commands=['infographic'])
    def infographic_handle(message):
        cache = _last_summary_cache.get(message.chat.id)
        if not cache:
            bot.reply_to(message, "⚠️ Chưa có bài nào. Dùng `/read <url>` trước!", parse_mode="Markdown")
            return
        wait_msg = bot.reply_to(message, "🎨 Đang tạo infographic...")
        path = _create_infographic(cache["title"], cache["summary"], cache["url"])
        if path.startswith("ERROR:"):
            bot.edit_message_text(f"❌ Lỗi: {path[6:]}", message.chat.id, wait_msg.message_id)
            return
        with open(path, "rb") as f:
            bot.send_photo(message.chat.id, f, caption=f"📊 *{cache['title'][:100]}*", parse_mode="Markdown")
        bot.delete_message(message.chat.id, wait_msg.message_id)
        try:
            os.remove(path)
        except Exception:
            pass

def _create_infographic(title: str, summary: str, url: str) -> str:
    """Creates a beautiful summary image and returns the file path."""
    try:
        from PIL import Image, ImageDraw, ImageFont
        import textwrap
        W, H = 900, 620
        DARK = (15, 23, 42)
        ACCENT = (99, 102, 241)
        WHITE = (255, 255, 255)
        GRAY = (148, 163, 184)
        LIGHT_BG = (30, 41, 59)
        img = Image.new("RGB", (W, H), DARK)
        draw = ImageDraw.Draw(img)
        draw.rectangle([(0, 0), (W, 6)], fill=ACCENT)
        try:
            font_title = ImageFont.truetype("arial.ttf", 20)
            font_body = ImageFont.truetype("arial.ttf", 15)
            font_small = ImageFont.truetype("arial.ttf", 12)
        except Exception:
            font_title = ImageFont.load_default()
            font_body = font_title
            font_small = font_title
        draw.rectangle([(25, 18), (W - 25, 82)], fill=LIGHT_BG, outline=ACCENT, width=1)
        title_wrapped = textwrap.fill(title[:90], width=62)
        draw.text((40, 28), title_wrapped, fill=WHITE, font=font_title)
        y = 100
        
        # Clean HTML out of summary if presence
        import re
        clean_summary = re.sub(r'<[^>]+>', '', summary)
        lines = clean_summary.replace("**", "").split("\n")
        
        for line in lines:
            if not line.strip():
                y += 6
                continue
            if any(line.strip().startswith(x) for x in ("1.", "2.", "3.", "🎯", "📌", "💡")):
                draw.text((35, y), line.strip(), fill=ACCENT, font=font_body)
                y += 26
            elif line.strip().startswith(("-", "•", "*")):
                for wl in textwrap.fill(line.strip(), width=76).split("\n"):
                    draw.text((50, y), wl, fill=WHITE, font=font_body)
                    y += 20
            else:
                for wl in textwrap.fill(line.strip(), width=80).split("\n"):
                    draw.text((35, y), wl, fill=GRAY, font=font_body)
                    y += 18
            if y > H - 55:
                draw.text((35, y), "...", fill=GRAY, font=font_body)
                break
        draw.rectangle([(0, H - 38), (W, H)], fill=LIGHT_BG)
        short_url = url[:72] + "..." if len(url) > 72 else url
        draw.text((25, H - 25), f"🔗 {short_url}", fill=GRAY, font=font_small)
        draw.text((W - 170, H - 25), "🤖 Powered by Gemini", fill=ACCENT, font=font_small)
        path = "infographic_temp.png"
        img.save(path, "PNG")
        return path
    except Exception as e:
        return f"ERROR:{e}"
